server:
  port: 12014
spring:
  application:
    name: microservice-cms
  jpa:
    database: MYSQL
    #database: POSTGRESQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        #dialect : org.hibernate.dialect.MySQL5Dialect
        dialect : org.hibernate.dialect.PostgreSQLDialect
  datasource:                           # 指定mysql数据源
    url: jdbc:mysql://127.0.0.1:3306/microservice_cms?useUnicode=true&amp;characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
    
#  datasource:                           # 指定postgresql数据源
#    url: jdbc:postgresql://127.0.0.1:5433/microservice_demo
#    driverClassName: org.postgresql.Driver
#    username: postgres  
#    password: postgres  
  redis:                               # 指定redis数据源
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

#rabbitmq: 
#     addresses: 127.0.0.1:5672
#     username: guest
#     password: guest
#     virtual-host: / 

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    hostname: demo
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}