server:
  port: 12009
spring:
  application: 
    name: microservice-flowable-web
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        dialect : org.hibernate.dialect.MySQL5Dialect
  datasource:                           
    url: jdbc:mysql://127.0.0.1:3306/microservice_flowable?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
    
#  admin: 
#      email: admin
#      password: admin
#      firstname: Test
#      lastname: Administrator
      
flowable: 
  check-process-definitions: false
    
#  thymeleaf:
#        cache: false
#    #    prefix: classpath:/templates/
#    #    suffix: .html
#    #    mode: HTML5
#    #    encoding: UTF-8
#    #    content-type: text/html
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true